package climenu

import (
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

type bootstrapYAML struct {
	Server struct {
		Hostname string `yaml:"hostname"`
	} `yaml:"server"`
	Storage struct {
		Driver   string `yaml:"driver"`
		SQLite   struct {
			Path string `yaml:"path"`
		} `yaml:"sqlite"`
		Postgres struct {
			DSN string `yaml:"dsn"`
		} `yaml:"postgres"`
	} `yaml:"storage"`
	Mailstore struct {
		Root string `yaml:"root"`
	} `yaml:"mailstore"`
	Seed struct {
		Enabled  bool   `yaml:"enabled"`
		Tenant   string `yaml:"tenant"`
		Domain   string `yaml:"domain"`
		Email    string `yaml:"email"`
		Password string `yaml:"password"`
		Name     string `yaml:"name"`
	} `yaml:"seed"`
	HTTP struct {
		PublicURL string   `yaml:"public_url"`
		Admins    []string `yaml:"admins"`
	} `yaml:"http"`
	TLS struct {
		CertFile     string `yaml:"cert_file"`
		KeyFile      string `yaml:"key_file"`
		CertsDir     string `yaml:"certs_dir"`
		AutoGenerate bool   `yaml:"auto_generate"`
	} `yaml:"tls"`
	Log struct {
		Level  string `yaml:"level"`
		Format string `yaml:"format"`
		File   string `yaml:"file"`
	} `yaml:"log"`
}

func (m *Menu) wizardSetup() error {
	u := m.ui
	u.Println("Мастер первичной настройки — создаст bootstrap YAML.")
	outPath := u.Prompt("Путь к конфигу", m.cfgPath)
	hostname := u.Prompt("Hostname (FQDN)", "mail.example.com")
	driver := strings.ToLower(u.Prompt("БД (sqlite/postgres)", "sqlite"))
	dataRoot := u.Prompt("Каталог данных", "./data")

	var cfg bootstrapYAML
	cfg.Server.Hostname = hostname
	cfg.Storage.Driver = driver
	cfg.Mailstore.Root = filepath.Join(dataRoot, "maildir")
	cfg.TLS.CertFile = filepath.Join(dataRoot, "certs", "server.crt")
	cfg.TLS.KeyFile = filepath.Join(dataRoot, "certs", "server.key")
	cfg.TLS.CertsDir = filepath.Join(dataRoot, "certs", "store")
	cfg.TLS.AutoGenerate = true

	switch driver {
	case "postgres", "postgresql":
		cfg.Storage.Driver = "postgres"
		cfg.Storage.Postgres.DSN = u.Prompt("Postgres DSN", "postgres://tayga:tayga@localhost:5432/tayga?sslmode=disable")
	default:
		cfg.Storage.Driver = "sqlite"
		cfg.Storage.SQLite.Path = filepath.Join(dataRoot, "tayga.db")
	}

	domain := u.Prompt("Домен seed", "example.com")
	email := u.Prompt("Email админа", "admin@"+domain)
	pass := u.Prompt("Пароль админа", "changeme")
	cfg.Seed.Enabled = true
	cfg.Seed.Tenant = "default"
	cfg.Seed.Domain = domain
	cfg.Seed.Email = email
	cfg.Seed.Password = pass
	cfg.Seed.Name = "Administrator"
	cfg.HTTP.PublicURL = u.Prompt("Public URL", "https://"+hostname)
	cfg.HTTP.Admins = []string{email}
	cfg.Log.Level = "info"
	cfg.Log.Format = "json"
	cfg.Log.File = u.Prompt("Файл логов (обязательно)", filepath.Join(dataRoot, "tayga.log"))

	for _, dir := range []string{
		filepath.Dir(outPath),
		cfg.Mailstore.Root,
		cfg.TLS.CertsDir,
		filepath.Dir(cfg.Log.File),
	} {
		if dir == "" || dir == "." {
			continue
		}
		if err := os.MkdirAll(dir, 0o750); err != nil {
			return err
		}
	}
	if cfg.Storage.Driver == "sqlite" {
		if err := os.MkdirAll(filepath.Dir(cfg.Storage.SQLite.Path), 0o750); err != nil {
			return err
		}
	}

	raw, err := yaml.Marshal(&cfg)
	if err != nil {
		return err
	}
	header := "# Tayga Mail — bootstrap (generated by tayga menu)\n# Policies live in DB; edit via Admin → Server or this menu.\n"
	if err := os.WriteFile(outPath, append([]byte(header), raw...), 0o640); err != nil {
		return err
	}
	m.cfgPath = outPath
	u.Printf("Записано %s\n", outPath)
	u.Println("Запуск: tayga-mail -config " + outPath)
	return nil
}

func (m *Menu) showConfigSummary() error {
	cfg, err := m.loadCfg()
	if err != nil {
		return err
	}
	m.ui.Printf("config:    %s\n", m.cfgPath)
	m.ui.Printf("hostname:  %s\n", cfg.Server.Hostname)
	m.ui.Printf("storage:   %s\n", cfg.Storage.Driver)
	if cfg.Storage.Driver == "postgres" {
		m.ui.Printf("dsn:       %s\n", redactDSN(cfg.Storage.Postgres.DSN))
	} else {
		m.ui.Printf("sqlite:    %s\n", cfg.Storage.SQLite.Path)
	}
	m.ui.Printf("maildir:   %s\n", cfg.Mailstore.Root)
	m.ui.Printf("public:    %s\n", cfg.HTTP.PublicURL)
	m.ui.Printf("admins:    %v\n", cfg.HTTP.Admins)
	m.ui.Printf("log.file:  %s\n", cfg.Log.File)
	m.ui.Printf("siem:      enabled=%v %s %s\n", cfg.SIEM.Enabled, cfg.SIEM.Protocol, cfg.SIEM.Address)
	return nil
}

func redactDSN(dsn string) string {
	at := strings.LastIndex(dsn, "@")
	if at < 0 {
		return dsn
	}
	colon := strings.LastIndex(dsn[:at], ":")
	scheme := strings.Index(dsn, "://")
	if scheme < 0 || colon <= scheme {
		return dsn
	}
	return dsn[:colon+1] + "***" + dsn[at:]
}
