// Shared stroke language for reader actions and document previews.
function designIcon(name) {
  const paths={reply:'M9 5 3 11l6 6M3 11h9a8 8 0 0 1 8 8','reply-all':'m8 4-6 6 6 6m5-12-6 6 6 6M7 10h6a8 8 0 0 1 8 8',trip:'M8 2h8v4H8zM5 6h14v15H5zM9 10v6m6-6v6',spam:'m7 3-4 4v10l4 4h10l4-4V7l-4-4zM12 7v6m0 4h.01',archive:'M3 3h18v5H3zM5 8v13h14V8M9 12h6',delete:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7',download:'M12 3v12m-5-5 5 5 5-5M4 17v4h16v-4',close:'m6 6 12 12M18 6 6 18'};
  return '<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round"><path d="'+(paths[name]||paths.download)+'"/></svg>';
}
function documentPreviewType(name) {
  const ext=String(name||'').split('.').pop().toLowerCase();
  return ({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',avif:'image/avif',pdf:'application/pdf'})[ext]||'';
}
async function openDocumentPreview({url,name,size}) {
  const focus=document.activeElement,dialog=document.createElement('dialog');dialog.className='document-preview';dialog.setAttribute('aria-label',name);
  const header=document.createElement('header'),title=document.createElement('strong');title.textContent=name;
  const download=document.createElement('button');download.type='button';download.className='btn-secondary btn-sm';download.textContent=t('download');download.disabled=true;
  const close=document.createElement('button');close.type='button';close.className='btn-secondary action-icon';close.title=mailImageText('Закрыть','Close');close.setAttribute('aria-label',close.title);close.innerHTML=designIcon('close');close.onclick=()=>dialog.close();header.append(title,download,close);
  const content=document.createElement('div');content.className='document-preview-content';content.setAttribute('role','status');content.textContent=mailImageText('Загрузка…','Loading…');dialog.append(header,content);document.body.append(dialog);dialog.showModal();
  const controller=new AbortController();let objectURL='',pdfDocument=null,renderTask=null;dialog.addEventListener('close',()=>{dialog.remove();controller.abort();if(objectURL)URL.revokeObjectURL(objectURL);try{renderTask?.cancel();pdfDocument?.destroy()?.catch(()=>{})}catch{}if(focus?.isConnected)focus.focus()},{once:true});
  try {
    if(size>64*1024*1024)throw new Error(mailImageText('Файл больше 64 МиБ. Используйте скачивание.','File exceeds 64 MiB. Use download.'));
    const headers={};if(state.tokens?.access_token)headers.Authorization='Bearer '+state.tokens.access_token;
    const response=await fetch(url,{headers,signal:controller.signal});if(!response.ok)throw new Error(mailImageText('Не удалось открыть файл','Unable to open file'));
    const blob=await response.blob();if(!dialog.open)return;if(blob.size>64*1024*1024)throw new Error(mailImageText("Файл больше 64 МиБ","File exceeds 64 MiB"));
    const type=documentPreviewType(name);objectURL=URL.createObjectURL(type?new Blob([blob],{type}):blob);download.disabled=false;
    download.onclick=()=>{const link=document.createElement('a');link.href=objectURL;link.download=name;link.click()};
    if(type.startsWith('image/')){const image=document.createElement('img');image.alt=name;image.src=objectURL;image.onerror=()=>{content.textContent=mailImageText('Изображение не удалось прочитать.','Unable to decode image.')};content.replaceChildren(image)}
    else if(type==='application/pdf'){
      const pdfjs=await import('/assets/pdfjs/pdf.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/assets/pdfjs/pdf.worker.mjs';
      if(!dialog.open)return;
      pdfDocument=await pdfjs.getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false,cMapUrl:'/assets/pdfjs/cmaps/',cMapPacked:true,standardFontDataUrl:'/assets/pdfjs/standard_fonts/',wasmUrl:'/assets/pdfjs/wasm/'}).promise;
      if(!dialog.open){pdfDocument.destroy();return}
      const nav=document.createElement('div');nav.className='pdf-preview-nav';const previous=document.createElement('button'),next=document.createElement('button'),pageLabel=document.createElement('span');for(const button of [previous,next]){button.type='button';button.className='btn-secondary btn-sm'}previous.textContent='‹';next.textContent='›';previous.setAttribute('aria-label',mailImageText('Предыдущая страница','Previous page'));next.setAttribute('aria-label',mailImageText('Следующая страница','Next page'));nav.append(previous,pageLabel,next);header.after(nav);
      let pageNumber=1;const render=async()=>{previous.disabled=true;next.disabled=true;const page=await pdfDocument.getPage(pageNumber);if(!dialog.open)return;const viewport=page.getViewport({scale:Math.min(2,Math.max(1,content.clientWidth-32)/page.getViewport({scale:1}).width,4096/page.getViewport({scale:1}).height)}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);canvas.setAttribute('aria-label',mailImageText('Страница PDF ','PDF page ')+pageNumber);content.replaceChildren(canvas);renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport});await renderTask.promise;pageLabel.textContent=pageNumber+' / '+pdfDocument.numPages;previous.disabled=pageNumber===1;next.disabled=pageNumber===pdfDocument.numPages;};
      const change=async(delta)=>{pageNumber+=delta;try{await render()}catch(error){if(dialog.open)content.textContent=error.message}};previous.onclick=()=>change(-1);next.onclick=()=>change(1);await render();
    }
    else content.textContent=mailImageText('Для этого формата доступно скачивание.','Download is available for this format.');
  }catch(error){if(error.name!=='AbortError'&&dialog.open)content.textContent=error.message}
}
function mountComposeDesign() {
  const panel=$('compose-panel');if(!panel||panel.dataset.designMounted)return;panel.dataset.designMounted='true';ensureComposeCC();
  for(const id of ['compose-to','compose-cc','compose-subject']){const input=$(id);if(!input)continue;const label=input.previousElementSibling;const row=document.createElement('div');row.className='compose-address-row';input.before(row);if(label?.tagName==='LABEL')row.append(label);row.append(input);}
  const footer=document.createElement('div');footer.className='compose-footer';const attachment=$('compose-attach');const label=attachment.previousElementSibling;const group=document.createElement('div');group.className='compose-file-control';if(label?.tagName==='LABEL')group.append(label);group.append(attachment);footer.append(group,panel.querySelector('.actions'));panel.append(footer,$('compose-msg'));
}
mountComposeDesign();
const selectedMailIDs=new Set();
function renderMailSelection(messages) {
 selectedMailIDs.clear();let bar=$('mail-selection');if(!bar){bar=document.createElement('div');bar.id='mail-selection';bar.className='mail-selection';$('mail-msg-list').before(bar)}bar.replaceChildren();bar.hidden=!messages.length;
 const all=document.createElement('input');all.type='checkbox';all.setAttribute('aria-label',mailImageText('Выбрать письма на этой странице','Select messages on this page'));bar.append(all);
 const count=document.createElement('span');count.className='meta';bar.append(count);const buttons=[];
 const update=()=>{count.textContent=mailImageText('Выбрано: ','Selected: ')+selectedMailIDs.size;all.checked=messages.length>0&&selectedMailIDs.size===messages.length;all.indeterminate=selectedMailIDs.size>0&&!all.checked;buttons.forEach(b=>b.disabled=!selectedMailIDs.size);};
 all.onchange=()=>{$('mail-msg-list').querySelectorAll('.mail-select').forEach(input=>{input.checked=all.checked;if(all.checked)selectedMailIDs.add(input.value);else selectedMailIDs.delete(input.value)});update()};
 for(const message of messages){const row=$('mail-msg-list').querySelector('[data-msg="'+CSS.escape(message.id)+'"]')?.parentElement;if(!row)continue;row.classList.add('selectable-mail');const input=document.createElement('input');input.className='mail-select';input.type='checkbox';input.value=message.id;input.setAttribute('aria-label',mailImageText('Выбрать письмо: ','Select message: ')+(message.subject||''));input.onchange=()=>{if(input.checked)selectedMailIDs.add(message.id);else selectedMailIDs.delete(message.id);update()};row.prepend(input);}
 for(const [action,label] of [['read',mailImageText('Прочитано','Mark read')],['unread',mailImageText('Не прочитано','Mark unread')],['archive',mailImageText('В архив','Archive')],['spam',mailImageText('В спам','Spam')],['delete',t('delete')]]) {const button=document.createElement('button');button.type='button';button.className='btn-secondary btn-sm';button.textContent=label;buttons.push(button);bar.append(button);button.onclick=async()=>{
  const ids=[...selectedMailIDs];if(action==='delete'&&!await askConfirm(mailImageText('Удалить выбранные письма: ','Delete selected messages: ')+ids.length+'?',{danger:true}))return;
  bar.querySelectorAll('button,input').forEach(e=>e.disabled=true);let completed=0;
  try{let spam;if(action==='spam'){spam=(mailState.mailboxes||[]).find(m=>m.name==='Junk');if(!spam)throw Error(mailImageText('Папка спама недоступна','Spam folder unavailable'));}
   for(const id of ids){const path='/api/v1/mail/messages/'+encodeURIComponent(id);if(action==='read'||action==='unread')await api(path,{method:'PATCH',body:JSON.stringify({seen:action==='read'})});else if(action==='spam')await api(path+'/move',{method:'POST',body:JSON.stringify({mailbox_id:spam.id})});else await api(path+(action==='archive'?'/archive':''),{method:action==='archive'?'POST':'DELETE'});completed++;selectedMailIDs.delete(id);}
   mailState.messageID='';await refreshMail();
  }catch(error){await askAlert(mailImageText('Обработано ','Processed ')+completed+'/'+ids.length+'. '+error.message);await refreshMailMessages();}
 };}
 update();
}

function calendarDisplayLabel(calendar){
 const defaults={default:['Календарь','Main calendar'],personal:['Личный календарь','Personal calendar'],work:['Рабочий календарь','Work calendar']};const names=defaults[calendar.name];
 if(names&&(!calendar.display_name||[...names,'default','Calendar'].includes(calendar.display_name)))return mailImageText(...names);
 return calendar.display_name||calendar.name||calendar.id;
}
function calendarEventLabel(event){return event.busy_only?mailImageText('Занято','Busy'):(event.summary||'—')}
let composeContactsCache=null,composeContactsLoading=null,composeContactsIdentity="";
async function composeContacts(){
 const identity=state.tokens?.access_token||"";if(identity!==composeContactsIdentity){composeContactsCache=null;composeContactsLoading=null;composeContactsIdentity=identity;}
 if(composeContactsCache)return composeContactsCache;if(composeContactsLoading)return composeContactsLoading;
 composeContactsLoading=(async()=>{const books=await api('/api/v1/contacts/books'),contacts=[];for(const book of books.books||[]){const result=await api('/api/v1/contacts/books/'+encodeURIComponent(book.id)+'/cards');for(const card of result.cards||[])if(card.email)contacts.push({name:card.fn||card.email,email:card.email})}const seen=new Set();return contacts.filter(c=>{const key=c.email.toLowerCase();if(seen.has(key))return false;seen.add(key);return true})})();
 try{const result=await composeContactsLoading;if(identity!==composeContactsIdentity)throw Error("Session changed");composeContactsCache=result;return result}finally{composeContactsLoading=null}
}
function mountComposeMentions(){
 const body=$('compose-body');if(!body)return;
 const popup=document.createElement('div');popup.className='compose-suggestions';popup.hidden=true;popup.id='compose-suggestions';popup.setAttribute('role','listbox');document.body.append(popup);let options=[],index=0,context=null,revision=0;
 const dismiss=()=>{revision++;popup.hidden=true;context=null;for(const id of ['compose-to','compose-cc','compose-body']){$(id)?.removeAttribute('aria-activedescendant');$(id)?.setAttribute('aria-expanded','false')}};
 const active=()=>{[...popup.children].forEach((button,i)=>button.setAttribute('aria-selected',String(i===index)));context?.field.setAttribute('aria-activedescendant','compose-option-'+index)};
 const choose=()=>{const contact=options[index],saved=context;if(!contact||!saved)return;dismiss();if(saved.range){const range=saved.range;range.deleteContents();const text=document.createTextNode('@'+contact.name+' ');range.insertNode(text);range.setStartAfter(text);range.collapse(true);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);saved.field.focus();const cc=$('compose-cc');if(cc){const existing=cc.value.split(/[,;]/).map(s=>s.trim()).filter(Boolean);if(!existing.some(s=>s.toLowerCase()===contact.email.toLowerCase()))existing.push(contact.email);cc.value=existing.join(', ');}}else{const input=saved.field;input.value=saved.prefix+contact.email+', ';input.focus();input.setSelectionRange(input.value.length,input.value.length)} };
 const suggest=async field=>{
  const stamp=++revision;let query='',prefix='',range=null;
  if(field===body){const selection=window.getSelection();if(!selection?.rangeCount||!selection.isCollapsed){dismiss();return}const cursor=selection.getRangeAt(0);if(cursor.startContainer.nodeType!==Node.TEXT_NODE||!body.contains(cursor.startContainer)){dismiss();return}const text=cursor.startContainer.textContent.slice(0,cursor.startOffset),match=text.match(/(?:^|\s)@([^@\s]*)$/);if(!match){dismiss();return}query=match[1];range=cursor.cloneRange();range.setStart(cursor.startContainer,cursor.startOffset-query.length-1);}
  else{if(field.selectionStart!==field.value.length){dismiss();return}const before=field.value.slice(0,field.selectionStart),last=Math.max(before.lastIndexOf(','),before.lastIndexOf(';'));prefix=field.value.slice(0,last+1);query=before.slice(last+1).trim().replace(/^@/,'');if(!query){dismiss();return}}
  try{const contacts=await composeContacts();if(stamp!==revision||!field.isConnected)return;options=contacts.filter(c=>(c.name+' '+c.email).toLowerCase().includes(query.toLowerCase())).slice(0,8);if(!options.length){dismiss();return}context={field,prefix,range};index=0;popup.replaceChildren();options.forEach((contact,i)=>{const button=document.createElement('button');button.type='button';button.id='compose-option-'+i;button.setAttribute('role','option');const name=document.createElement('strong'),email=document.createElement('span');name.textContent=contact.name;email.textContent=contact.email;button.append(name,email);button.onmousedown=e=>e.preventDefault();button.onclick=()=>{index=i;choose()};popup.append(button)});const rect=field.getBoundingClientRect();popup.style.left=Math.max(8,Math.min(rect.left,window.innerWidth-320))+'px';popup.style.top=Math.min(rect.bottom,window.innerHeight-280)+'px';popup.hidden=false;field.setAttribute('aria-expanded','true');active();}catch{dismiss()}
 };
 for(const id of ['compose-to','compose-cc','compose-body']){const field=$(id);if(!field)continue;field.setAttribute('aria-controls',popup.id);field.setAttribute('aria-autocomplete','list');field.addEventListener('input',()=>suggest(field));field.addEventListener('keydown',event=>{if(popup.hidden||context?.field!==field)return;if(['ArrowDown','ArrowUp','Enter','Escape','Tab'].includes(event.key)){if(event.key==='Escape'||event.key==='Tab'){dismiss();if(event.key==='Escape')event.preventDefault();return}event.preventDefault();if(event.key==='Enter')choose();else{index=(index+(event.key==='ArrowDown'?1:-1)+options.length)%options.length;active()}}});field.addEventListener('blur',()=>setTimeout(()=>{if(document.activeElement!==field&&!popup.contains(document.activeElement))dismiss()},100));}
 document.addEventListener('click',event=>{if(!popup.contains(event.target)&&!['compose-to','compose-cc','compose-body'].includes(event.target.id))dismiss()});
 $('btn-compose-close')?.addEventListener('click',dismiss);$('btn-compose-send')?.addEventListener('click',dismiss);
 const hint=document.createElement('p');hint.className='compose-shortcut-hint meta';hint.textContent=mailImageText('@ — контакт и копия · Ctrl/⌘ B, I, U — форматирование','@ — mention and CC · Ctrl/⌘ B, I, U — formatting');$('compose-rte').after(hint);
}
mountComposeMentions();
function mountCalendarPlaceSearch(){
 const location=$('cal-location');if(!location||$('cal-place-search'))return;
 const row=document.createElement('div');row.className='calendar-place-tools';const search=document.createElement('button');search.id='cal-place-search';search.className='btn-secondary btn-sm';search.type='button';search.textContent=mailImageText('Найти на карте','Find on map');const map=document.createElement('a');map.className='btn-secondary btn-sm';map.target='_blank';map.rel='noopener noreferrer';map.hidden=true;map.textContent=mailImageText('Открыть карту','Open map');const results=document.createElement('div');results.className='calendar-place-results';results.setAttribute('role','status');const hint=document.createElement('p');hint.className='meta';hint.style.fontSize='.75rem';hint.textContent=mailImageText('Поиск отправляет только введённое место в Photon. Карта: © OpenStreetMap contributors.','Search sends only the entered place to Photon. Map: © OpenStreetMap contributors.');row.append(search,map);location.after(row,results,hint);
 location.addEventListener('input',()=>{delete location.dataset.geo;map.hidden=true;results.replaceChildren()});
 search.onclick=async()=>{const query=location.value.trim();if(query.length<3){results.textContent=mailImageText('Введите адрес или название места','Enter an address or place name');return}search.disabled=true;results.textContent=mailImageText('Поиск…','Searching…');try{const data=await api('/api/v1/calendar/places?q='+encodeURIComponent(query));results.replaceChildren();for(const place of data.places||[]){const button=document.createElement('button');button.type='button';button.className='btn-secondary btn-sm';button.textContent=place.label;button.onclick=()=>{location.value=place.label;location.dataset.geo=place.geo;const [lat,lon]=place.geo.split(';');map.href='https://www.openstreetmap.org/?mlat='+encodeURIComponent(lat)+'&mlon='+encodeURIComponent(lon)+'#map=16/'+encodeURIComponent(lat)+'/'+encodeURIComponent(lon);map.hidden=false;results.textContent=mailImageText('Точка выбрана: ','Point selected: ')+place.geo;};results.append(button)}if(!data.places?.length)results.textContent=mailImageText('Место не найдено. Уточните адрес.','Place not found. Refine the address.')}catch(error){results.textContent=error.message}finally{search.disabled=false}};
}
mountCalendarPlaceSearch();
function findCommonSlots(users,start,end,duration,limit=3){
 const intervals=users.filter(u=>u.available==='local').flatMap(u=>u.busy||[]).map(b=>[Date.parse(b.start),Date.parse(b.end)]);const slots=[];
 for(let time=Math.ceil(start/1800000)*1800000;time+duration<=end&&slots.length<limit;time+=1800000){const local=new Date(time),finish=new Date(time+duration);if([0,6].includes(local.getDay())||local.getHours()<9||finish.getHours()*60+finish.getMinutes()>18*60||finish.getDate()!==local.getDate())continue;if(!intervals.some(([a,b])=>a<time+duration&&b>time)){slots.push(time);time+=Math.max(0,duration-1800000)}}return slots;
}
function mountCalendarPlanning(){
 const block=$('cal-freebusy')?.closest('.cal-freebusy-block');if(!block||$('cal-find-time'))return;const button=document.createElement('button');button.type='button';button.id='cal-find-time';button.className='btn-secondary btn-sm';button.textContent=mailImageText('Подобрать время','Find a time');block.querySelector('.actions').append(button);
 button.onclick=async()=>{addCalAttendeesFromInput();const start=Date.parse(localInputToISO($('cal-start').value)),finish=Date.parse(localInputToISO($('cal-end').value)),duration=finish-start,host=$('cal-freebusy');if(!Number.isFinite(duration)||duration<=0){host.textContent=mailImageText('Укажите начало и конец события','Set the event start and end');return}button.disabled=true;try{const emails=[...new Set([state.me?.email||state.email,...calState.attendees.map(a=>a.email)].filter(Boolean))];if(!emails.length)throw Error(mailImageText('Добавьте участников','Add attendees'));const horizon=start+7*86400000,result=await api('/api/v1/calendar/freebusy?'+new URLSearchParams({emails:emails.join(','),from:new Date(start).toISOString(),to:new Date(horizon).toISOString()}));host.replaceChildren();const users=result.users||[],unknown=users.filter(u=>u.available!=='local'),hint=document.createElement('p');hint.className='meta';hint.textContent=mailImageText('Следующие 7 дней, пн–пт 09:00–18:00 по вашему времени.','Next 7 days, Mon–Fri 09:00–18:00 in your timezone.')+(unknown.length?mailImageText(' Занятость неизвестна: ',' Availability unknown: ')+unknown.map(u=>u.email).join(', '):'');host.append(hint);if(!users.some(u=>u.available==='local'))return;const slots=findCommonSlots(users,start,horizon,duration);for(const slot of slots){const choose=document.createElement('button');choose.type='button';choose.className='btn-secondary btn-sm';choose.textContent=new Date(slot).toLocaleString(lang==='en'?'en-GB':'ru-RU');choose.onclick=()=>{const local=value=>new Date(value-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16);$('cal-start').value=local(slot);$('cal-end').value=local(slot+duration);loadCalFreeBusy()};host.append(choose)}if(!slots.length){const message=document.createElement('p');message.textContent=mailImageText('Общего свободного времени не найдено','No common available time found');host.append(message)}}catch(error){host.textContent=error.message}finally{button.disabled=false}};
}
mountCalendarPlanning();

function mountContactDesign(){
 const original=$('btn-contact-new'),head=$('contact-book-title')?.parentElement;if(original&&head&&!$('btn-contact-add-visible')){const button=document.createElement('button');button.type='button';button.id='btn-contact-add-visible';button.className='btn-spray btn-sm';button.textContent=mailImageText('+ Добавить контакт','+ Add contact');button.onclick=()=>original.click();head.insertBefore(button,$('btn-contacts-refresh'));}
}
mountContactDesign();

function mountDKIMGenerator(){
 const actions=$('settings-home')?.querySelector('.actions');if(!actions)return;
 const entry=document.createElement('button');entry.type='button';entry.className='btn-secondary';entry.textContent=mailImageText('DKIM: ключи и DNS','DKIM: keys and DNS');actions.prepend(entry);
 entry.onclick=()=>{
 const dialog=document.createElement('dialog');dialog.className='dkim-generator';
 const heading=document.createElement('h3');heading.className='heading';heading.textContent=entry.textContent;
 const intro=document.createElement('p');intro.className='meta';intro.textContent=mailImageText('Создайте RSA-ключ 2048 бит, скачайте закрытый ключ и опубликуйте TXT-запись. Новый ключ не заменяет действующий автоматически.','Generate a 2048-bit RSA key, download the private key and publish the TXT record. Existing signing keys are not replaced automatically.');
 const form=document.createElement('form'),domain=document.createElement('input'),selector=document.createElement('input');
 domain.className=selector.className='field-input';domain.required=selector.required=true;domain.placeholder='example.com';selector.value='tayga';selector.pattern='[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}';
 for(const [label,input] of [[mailImageText('Домен отправителя','Sending domain'),domain],[mailImageText('Селектор (имя ключа)','Selector (key name)'),selector]]){const field=document.createElement('label');field.className='field';field.textContent=label;field.append(input);form.append(field)}
 const generate=document.createElement('button');generate.type='submit';generate.className='btn-spray';generate.textContent=mailImageText('Сгенерировать ключ','Generate key');form.append(generate);
 const result=document.createElement('section'),status=document.createElement('p');status.className='msg';status.setAttribute('role','status');
 const close=document.createElement('button');close.type='button';close.className='btn-secondary';close.textContent=t('close');close.onclick=()=>dialog.close();dialog.append(heading,intro,form,status,result,close);document.body.append(dialog);dialog.showModal();domain.focus();dialog.addEventListener('close',()=>{result.replaceChildren();dialog.remove()},{once:true});
 form.onsubmit=async event=>{event.preventDefault();generate.disabled=true;status.textContent='';result.replaceChildren();try{let key=await api('/api/v1/admin/dkim/generate',{method:'POST',body:JSON.stringify({domain:domain.value,selector:selector.value})});if(!dialog.open)return;
 for(const [label,value] of [[mailImageText('TXT — полное имя записи','TXT — full record name'),key.dns_name],[mailImageText('TXT — значение записи','TXT — record value'),key.dns_value]]){const field=document.createElement('label');field.className='field';field.textContent=label;const input=document.createElement('textarea');input.className='field-input';input.readOnly=true;input.rows=value.length>100?4:1;input.value=value;const copy=document.createElement('button');copy.type='button';copy.className='btn-secondary btn-sm';copy.textContent=mailImageText('Копировать','Copy');copy.onclick=async()=>{try{await navigator.clipboard.writeText(value)}catch{input.select()}};field.append(input,copy);result.append(field)}
 const hint=document.createElement('p');hint.className='meta';hint.textContent=mailImageText('Тип DNS: TXT, TTL: 3600. Если панель DNS добавляет домен сама, укажите только '+key.selector+'._domainkey. Значение вставьте одной строкой: DNS-провайдер должен разбить длинную TXT-запись на части до 255 байт. Закрытый ключ в DNS не публикуется.','DNS type: TXT, TTL: 3600. If your DNS panel appends the domain, enter only '+key.selector+'._domainkey. Paste the value as one line; your DNS provider must split long TXT records into chunks of at most 255 bytes. Never publish the private key.');
 const download=document.createElement('button');download.type='button';download.className='btn-spray';download.textContent=mailImageText('Скачать закрытый ключ (.pem)','Download private key (.pem)');download.onclick=()=>{const url=URL.createObjectURL(new Blob([key.private_key],{type:'application/x-pem-file'}));const link=document.createElement('a');link.href=url;link.download=key.domain+'-'+key.selector+'.pem';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 const setup=document.createElement('p');setup.className='meta';setup.textContent=mailImageText('Установите PEM на сервере с правами 0600 для пользователя службы. В «Сервер → SMTP → DKIM» задайте domain='+key.domain+', selector='+key.selector+' и private_key_file (путь к PEM). Включите enabled после публикации DNS и перезапустите службу. Скачайте ключ до закрытия окна: он не сохраняется в браузере.','Install the PEM on the server with mode 0600 for the service user. Set domain='+key.domain+', selector='+key.selector+' and private_key_file under Server → SMTP → DKIM. Enable signing after publishing DNS and restart the service. Download the key before closing: it is not persisted in the browser.');result.append(hint,download,setup);
 }catch(error){status.textContent=error.message}finally{generate.disabled=false}};
 };
}
mountDKIMGenerator();
