// Visual rules are stored with their generated Sieve script, so they survive reloads.
const visualRules = {rules:[], scripts:[], dirty:false, unreadable:false};
function sieveQuote(value){if(/[\x00-\x1f\x7f]/.test(String(value)))throw Error(mailImageText('Уберите переносы строк и управляющие символы','Remove line breaks and control characters'));return '"'+String(value).replace(/\\/g,'\\\\').replace(/"/g,'\\"')+'"'}
function generateVisualSieve(rules){
 const active=rules.filter(rule=>rule.enabled!==false);
 const lines=['# tayga-rules-v1 '+JSON.stringify(rules),'require ["fileinto"];'];
 for(const rule of active){
  if(!rule.conditions.length)throw Error(mailImageText('Добавьте хотя бы одно условие','Add at least one condition'));
  const conditions=rule.conditions.map(condition=>{
   if(!['From','To','Cc','Subject'].includes(condition.field)||!['contains','is','not_contains'].includes(condition.operator)||!condition.value.trim())throw Error(mailImageText('Заполните условие правила','Complete the rule condition'));
   return (condition.operator==='not_contains'?'not ':'')+'header :'+(condition.operator==='is'?'is':'contains')+' :comparator "i;ascii-casemap" '+sieveQuote(condition.field)+' '+sieveQuote(condition.value.trim());
  });
  lines.push('if '+(conditions.length===1?conditions[0]:(rule.match==='any'?'anyof':'allof')+' ('+conditions.join(', ')+')')+' {');
  if(rule.action==='fileinto'){if(!rule.destination.trim())throw Error(mailImageText('Выберите папку','Select a folder'));lines.push('  fileinto '+sieveQuote(rule.destination.trim())+';')}
  else if(rule.action==='keep')lines.push('  keep;');
  else if(rule.action==='discard')lines.push('  discard;');
  else throw Error('Unsupported rule action');
  if(rule.stop!==false)lines.push('  stop;');lines.push('}');
 }
 if(!active.length)lines.push('keep;');
 return lines.join('\n')+'\n';
}
function refreshVisualRules(scripts){
 visualRules.scripts=scripts||[];
 if(!visualRules.dirty){const saved=visualRules.scripts.find(script=>script.name==='visual-rules');if(saved){try{const first=saved.script.split('\n')[0];if(!first.startsWith('# tayga-rules-v1 '))throw Error('Not a generated script');if(first.startsWith('# tayga-rules-v1 ')){const rules=JSON.parse(first.slice('# tayga-rules-v1 '.length));if(!Array.isArray(rules)||!rules.every(rule=>typeof rule.name==='string'&&Array.isArray(rule.conditions)&&rule.conditions.every(c=>typeof c.value==='string')))throw Error('Invalid visual rule metadata');visualRules.rules=rules;visualRules.unreadable=false}}catch(error){visualRules.unreadable=true;setMsg($('visual-rule-msg'),mailImageText('Не удалось прочитать правила. Исходный скрипт сохранён в расширенном редакторе.','Cannot read visual rules. The script is preserved in the advanced editor.'),'err')}}else {visualRules.rules=[];visualRules.unreadable=false;}}
 $('btn-rules-save').disabled=visualRules.unreadable;
 renderVisualRules();
}
function renderVisualRules(){
 const list=$('visual-rule-list');if(!list)return;list.replaceChildren();
 if(!visualRules.rules.length){const empty=document.createElement('div');empty.className='rule-empty';empty.innerHTML='<strong>'+mailImageText('Правил пока нет','No rules yet')+'</strong><p>'+mailImageText('Например: если отправитель — коллега, переместить письмо в рабочую папку.','For example: if the sender is a colleague, move the message into a work folder.')+'</p>';list.append(empty)}
 visualRules.rules.forEach((rule,index)=>{
  const row=document.createElement('div');row.className='visual-rule-row';const enabled=document.createElement('input');enabled.type='checkbox';enabled.checked=rule.enabled!==false;enabled.setAttribute('aria-label',mailImageText('Включить правило: ','Enable rule: ')+rule.name);enabled.onchange=()=>{rule.enabled=enabled.checked;visualRules.dirty=true};
  const summary=document.createElement('button');summary.type='button';summary.className='rule-summary';const title=document.createElement('strong');title.textContent=rule.name;const text=document.createElement('small');text.textContent=rule.conditions.map(c=>({From:mailImageText('Отправитель','Sender'),To:mailImageText('Получатель','Recipient'),Cc:mailImageText('Копия','Cc'),Subject:mailImageText('Тема','Subject')}[c.field]||c.field)+' '+c.value).join(rule.match==='any'?' / ':' + ')+' → '+(rule.action==='fileinto'?rule.destination:rule.action==='discard'?mailImageText('Удалить','Discard'):mailImageText('Оставить во входящих','Keep in inbox'));summary.append(title,text);summary.onclick=()=>openVisualRule(index);row.append(enabled,summary);
  for(const [label,icon,run] of [[mailImageText('Выше','Move up'),'up',()=>{if(index){[visualRules.rules[index-1],visualRules.rules[index]]=[visualRules.rules[index],visualRules.rules[index-1]];visualRules.dirty=true;renderVisualRules()}}],[mailImageText('Удалить правило','Delete rule'),'delete',()=>{visualRules.rules.splice(index,1);visualRules.dirty=true;renderVisualRules()}]]){const button=document.createElement('button');button.type='button';button.className='btn-secondary rule-icon';button.title=label;button.setAttribute('aria-label',label);button.innerHTML=icon==='up'?'<span aria-hidden="true">↑</span>':designIcon(icon);button.onclick=run;row.append(button)}list.append(row);
 });
}
async function openVisualRule(index=-1){
 const existing=visualRules.rules[index];const rule=existing?JSON.parse(JSON.stringify(existing)):{name:'',enabled:true,match:'all',conditions:[{field:'From',operator:'contains',value:''}],action:'fileinto',destination:'',stop:true};
 const dialog=document.createElement('dialog');dialog.className='visual-rule-dialog';dialog.setAttribute('aria-label',mailImageText('Конструктор правила','Rule builder'));
 const form=document.createElement('form');form.innerHTML=`<header><strong>${mailImageText('Конструктор правила','Rule builder')}</strong><button type="button" data-rule-close class="btn-icon" aria-label="${t('close')}">×</button></header><label>${mailImageText('Название правила','Rule name')}<input class="field-input" name="name" required maxlength="100" placeholder="${mailImageText('Например: письма от команды','For example: messages from the team')}" value="${escapeHtml(rule.name)}"></label><h4>${mailImageText('Когда приходит письмо','When a message arrives')}</h4><select name="match" class="field-input"><option value="all">${mailImageText('Совпадают все условия','All conditions match')}</option><option value="any">${mailImageText('Совпадает хотя бы одно условие','Any condition matches')}</option></select><div data-rule-conditions></div><button type="button" class="btn-secondary btn-sm" data-add-condition>${mailImageText('+ Условие','+ Condition')}</button><h4>${mailImageText('Выполнить действие','Then do this')}</h4><select name="action" class="field-input"><option value="fileinto">${mailImageText('Переместить в папку','Move to folder')}</option><option value="keep">${mailImageText('Оставить во входящих','Keep in inbox')}</option><option value="discard">${mailImageText('Удалить без помещения в корзину','Discard without moving to trash')}</option></select><label data-folder-label>${mailImageText('Папка назначения','Destination folder')}<input name="destination" class="field-input" list="rule-folder-options" value="${escapeHtml(rule.destination||'')}" placeholder="Archive"><datalist id="rule-folder-options"></datalist></label><p class="meta" data-action-hint></p><label class="rule-check"><input type="checkbox" name="stop" ${rule.stop!==false?'checked':''}> ${mailImageText('Не выполнять следующие правила после совпадения','Stop processing further rules after a match')}</label><details><summary>${mailImageText('Предпросмотр Sieve','Sieve preview')}</summary><pre data-rule-preview></pre></details><p role="status" data-rule-error></p><footer><button type="button" class="btn-secondary" data-rule-close>${t('cancel')}</button><button class="btn-spray" type="submit">${mailImageText('Добавить в список правил','Add to rules')}</button></footer>`;
 dialog.append(form);document.body.append(dialog);dialog.onclose=()=>dialog.remove();form.elements.match.value=rule.match;form.elements.action.value=rule.action;
 const conditions=form.querySelector('[data-rule-conditions]');
 const addCondition=(condition)=>{
  const row=document.createElement('div');row.className='rule-condition';row.innerHTML=`<select data-field class="field-input" aria-label="${mailImageText('Поле письма','Message field')}">${[['From','Отправитель','Sender'],['To','Получатель','Recipient'],['Cc','Копия','Cc'],['Subject','Тема','Subject']].map(([value,ru,en])=>'<option value="'+value+'">'+mailImageText(ru,en)+'</option>').join('')}</select><select data-operator class="field-input" aria-label="${mailImageText('Сравнение','Comparison')}"><option value="contains">${mailImageText('содержит','contains')}</option><option value="is">${mailImageText('равно','equals')}</option><option value="not_contains">${mailImageText('не содержит','does not contain')}</option></select><input class="field-input" data-value required placeholder="colleague@example.com" list="rule-email-options" value="${escapeHtml(condition.value)}"><button type="button" class="btn-secondary rule-icon" aria-label="${mailImageText('Удалить условие','Remove condition')}">×</button><small>${mailImageText('Сравнение без учёта регистра. «Равно» сравнивает весь заголовок; для адреса или части темы выберите «содержит».','Case-insensitive comparison. Use equals for a full header value and contains for part of a subject.')}</small>`;row.querySelector('[data-field]').value=condition.field;row.querySelector('[data-operator]').value=condition.operator;row.querySelector('button').onclick=()=>{row.remove();update()};conditions.append(row);row.querySelector('[data-field]').onchange=event=>{const input=row.querySelector('[data-value]');input.setAttribute('list',event.target.value==='Subject'?'':'rule-email-options');input.placeholder=event.target.value==='Subject'?mailImageText('Текст в теме письма','Text in the subject'):'colleague@example.com'};
 };
 const collect=()=>({...rule,name:form.elements.name.value.trim(),match:form.elements.match.value,conditions:[...conditions.children].map(row=>({field:row.querySelector('[data-field]').value,operator:row.querySelector('[data-operator]').value,value:row.querySelector('[data-value]').value})),action:form.elements.action.value,destination:form.elements.destination.value,stop:form.elements.stop.checked});
 const update=()=>{const action=form.elements.action.value;form.querySelector('[data-folder-label]').hidden=action!=='fileinto';form.elements.destination.required=action==='fileinto';form.querySelector('[data-action-hint]').textContent=action==='discard'?mailImageText('Письмо будет удалено без возможности восстановления. Для обычного удаления лучше переместить в Trash.','Messages are discarded permanently. Move to Trash for recoverable deletion.'):mailImageText('Правила выполняются сверху вниз для новых входящих писем.','Rules run from top to bottom for new incoming messages.');try{form.querySelector('[data-rule-preview]').textContent=generateVisualSieve([collect()])}catch(error){form.querySelector('[data-rule-preview]').textContent=error.message}};
 rule.conditions.forEach(addCondition);form.querySelector('[data-add-condition]').onclick=()=>{addCondition({field:'Subject',operator:'contains',value:''});update()};form.querySelectorAll('[data-rule-close]').forEach(button=>button.onclick=()=>dialog.close());form.oninput=update;form.onchange=update;
 const addresses=document.createElement('datalist');addresses.id='rule-email-options';for(const card of contactState.cards||[]){if(card.email){const option=document.createElement('option');option.value=card.email;option.label=card.fn||'';addresses.append(option)}}form.append(addresses);
 form.onsubmit=event=>{event.preventDefault();try{const value=collect();generateVisualSieve([value]);if(index<0)visualRules.rules.push(value);else visualRules.rules[index]=value;visualRules.dirty=true;renderVisualRules();dialog.close()}catch(error){form.querySelector('[data-rule-error]').textContent=error.message}};
 update();dialog.showModal();form.elements.name.focus();
 try{const books=await api('/api/v1/contacts/books');const results=await Promise.allSettled((books.books||[]).slice(0,5).map(book=>api('/api/v1/contacts/books/'+encodeURIComponent(book.id)+'/cards')));const seen=new Set([...addresses.children].map(option=>option.value));for(const result of results){if(result.status!=='fulfilled')continue;for(const card of result.value.cards||[]){if(card.email&&!seen.has(card.email)){seen.add(card.email);const option=document.createElement('option');option.value=card.email;option.label=card.fn||'';addresses.append(option)}}}}catch(error){/* Email addresses can also be entered directly. */}
 try{const data=await api('/api/v1/mail/mailboxes');const choices=form.querySelector('#rule-folder-options');for(const folder of data.mailboxes||[]){const option=document.createElement('option');option.value=folder.name;choices.append(option)}}catch(error){/* A destination can still be entered manually. */}
}
async function saveVisualRules(){
 const button=$('btn-rules-save');button.disabled=true;
 try{const script=generateVisualSieve(visualRules.rules);const manual=visualRules.scripts.find(item=>item.active&&item.name!=='visual-rules');if(manual&&!await askConfirm(mailImageText('Активировать визуальные правила вместо скрипта «','Activate visual rules instead of script “')+manual.name+mailImageText('»? Исходный скрипт останется в расширенном редакторе.','”? The original script remains in the advanced editor.')))return;
 await api('/api/v1/sieve/scripts/visual-rules',{method:'PUT',body:JSON.stringify({script,active:true})});visualRules.dirty=false;await refreshSieve();setMsg($('visual-rule-msg'),mailImageText('Правила сохранены и включены','Rules saved and activated'),'ok');
 }catch(error){setMsg($('visual-rule-msg'),error.message,'err')}finally{button.disabled=false}
}
function mountVisualRuleBuilder(){
 const host=$('app-filters');if(!host)return;
 const card=document.createElement('section');card.className='card visual-rule-builder';card.innerHTML=`<header><div><h3>${mailImageText('Правила обработки писем','Message rules')}</h3><p class="meta">${mailImageText('Выберите условия и действия. Знание Sieve не требуется.','Choose conditions and actions. No Sieve knowledge required.')}</p></div><button type="button" id="btn-rule-new" class="btn-spray">${mailImageText('+ Создать правило','+ Create rule')}</button></header><div id="visual-rule-list"></div><footer><button id="btn-rules-save" type="button" class="btn-spray">${mailImageText('Сохранить и включить','Save and activate')}</button><button type="button" id="btn-rules-reload" class="btn-secondary">${t('refresh')}</button></footer><p id="visual-rule-msg" role="status"></p>`;host.prepend(card);$('btn-rule-new').onclick=()=>openVisualRule();$('btn-rules-save').onclick=saveVisualRules;$('btn-rules-reload').onclick=async()=>{if(visualRules.dirty&&!await askConfirm(mailImageText('Отменить несохранённые изменения?','Discard unsaved changes?')))return;visualRules.dirty=false;refreshSieve()};
 const original=$('sieve-body')?.closest('.card');if(original){const details=document.createElement('details');details.className='advanced-sieve';const summary=document.createElement('summary');summary.textContent=mailImageText('Расширенный редактор Sieve и сохранённые скрипты','Advanced Sieve editor and saved scripts');original.before(details);details.append(summary,original)}renderVisualRules();
}
mountVisualRuleBuilder();
